version: '3.7'

services:

  lutrisweb:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - type: bind
        source: .
        target: /app

    ports:
      - "8008:8000"
    restart: on-failure
    stdin_open: true
    tty: true
    depends_on:
      - lutrisdb
      - lutriscache
      - lutrisfrontend

  lutrisfrontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    volumes:
      - type: bind
        source: .
        target: /app
    stdin_open: true
    tty: true

  celery_worker:
    build:
      context: .
    volumes:
      - type: volume
        source: media
        target: /app/media
        volume:
          nocopy: true
    depends_on:
      - lutrisdb
      - lutriscache
    command: celery worker -A lutrisweb.celery.app -B -l info

  lutrisdb:
    restart: unless-stopped
    image: postgres:12
    ports:
      - "5430:5432"
    volumes:
      - postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 'lutris'
      POSTGRES_USER: 'lutris'
      POSTGRES_PASSWORD: 'admin'

  lutriscache:
    restart: unless-stopped
    image: redis:6.0.1
    volumes:
      - redisdata:/data


volumes:
  postgresql:
  media:
  redisdata:
